const allRoles = {
  resident: [
    "getProfile",
    "updateProfile",
    "viewAnnouncements",
    "viewContracts",
    "createFeedbacks",
    "getFeedbacks",
    "manageFeedbacks",
    "getInvoices",
    "getInvoiceDetails",
    "viewServices",
    "registerService",
    "getApartments",
    "getServiceTypes",
    "getServiceRegistrations",
  ],
  manager: [
    "getProfile",
    "updateProfile",
    "getUsers",
    "getApartments",
    "viewAnnouncements",
    "manageAnnouncements",
    "manageContracts",
    "manageFeedbacks",
    "getFeedbacks",
    "getInvoices",
    "manageInvoices",
    "getInvoiceDetails",
    "manageInvoiceDetails",
    "manageServices",
    "manageApartments",
    "manageApartmentTypes",
    "getServiceTypes",
    "manageServiceTypes",
    "getServiceRegistrations",
    "manageServiceRegistrations",
    "viewReports",
  ],
  admin: [
    "getProfile",
    "updateProfile",
    "getUsers",
    "manageUsers",
    "getApartments",
    "manageApartments",
    "manageAnnouncements",
    "manageContracts",
    "manageFeedbacks",
    "getFeedbacks",
    "getInvoices",
    "manageInvoices",
    "getInvoiceDetails",
    "manageInvoiceDetails",
    "manageServices",
    "manageApartments",
    "manageApartmentTypes",
    "getServiceTypes",
    "manageServiceTypes",
    "getServiceRegistrations",
    "manageServiceRegistrations",
    "managePermissions",
    "viewAnnouncements",
    "viewReports",
    'respondToFeedbacks',
    "systemConfig",
    "admin"
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
