name: GitGuardian Scan

on:
  push:
  pull_request:

jobs:
  scan-for-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ggshield
        run: pip install ggshield

      - name: Run GitGuardian Scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan repo .
